from dataclasses import dataclass
from typing import List
import uuid


@dataclass
class Page:
    """Represents a single page extracted from a PDF document.
    
    Attributes:
        number: The page number (1-indexed).
        content: The text content of the page.
    """
    number: int
    content: str


@dataclass
class Chunk:
    """Represents a text chunk extracted from a document page.
    
    A chunk is a subdivision of a page, typically created by the chunking service
    for efficient processing and retrieval.
    
    Attributes:
        id: Unique identifier for this chunk.
        filename: Name of the source PDF file.
        page_number: The page number this chunk originated from.
        text: The actual text content of the chunk.
        score: Similarity score from vector search (0-1). Defaults to 0.0.
    """
    id: str
    filename: str
    page_number: int
    text: str
    score: float = 0.0


@dataclass
class Document:
    """Represents a complete PDF document with its pages and chunks.
    
    Attributes:
        id: Unique identifier for this document.
        filename: Path or name of the PDF file.
        pages: List of extracted pages.
        chunks: List of text chunks created from the pages.
    """
    id: str
    filename: str
    pages: List[Page]
    chunks: List[Chunk]

    @staticmethod
    def from_file(file_path: str, pages_text: List[Page]) -> "Document":
        """Create a Document instance from a file.
        
        Args:
            file_path: Path to the PDF file.
            pages_text: List of extracted pages from the PDF.
        
        Returns:
            A new Document instance with auto-generated ID and empty chunks list.
        """
        return Document(
            id=str(uuid.uuid4()), 
            filename=file_path, 
            pages=pages_text, 
            chunks=[]
        )
    
    def add_chunks(self, chunks: List[Chunk]) -> None:
        """Add text chunks to the document.
        
        Args:
            chunks: List of chunks to add to this document.
        """
        self.chunks = chunks


@dataclass
class Question:
    """Represents a user question to be answered by the RAG system.
    
    Attributes:
        text: The question text.
    """
    text: str


@dataclass
class Answer:
    """Represents an answer generated by the RAG system.
    
    Attributes:
        text: The generated answer text from the LLM.
        used_chunks: The source chunks used to generate this answer.
    """
    text: str
    used_chunks: List[Chunk]
